<a href="https://colab.research.google.com/github/neilkazimierzsheridan/TFDC/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Intro to tensors


In [2]:
print(tf.__version__)

2.5.0


Making tensors with tf.constant()


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check ndim (number of dimensions)
scalar.ndim

0

In [5]:
#here a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#ndim?
vector.ndim

1

In [7]:
#now a matrix
matrix = tf.constant([[10,7],
[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8., 9.]], dtype=tf.float16)
#specifiy datatype with dtype as floating point number 16
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
#Now a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
#so we made ndim of 3 with this one, but tensor is n dimensional
tensor.ndim

3

In [13]:
#making tensors with tf.variable and tf.constant
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#change an element in changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
#change an element in the tf.constant created tensor - hmmm lol
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

Creating Random Tensors!

In [16]:
#arbitrary size with random numbers 
#used to initialize before learning

#two random but the same sensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape=(3,2)) #normal distribution
random_2

random_1, random_2, random_1 == random_2 #equal? Not if I change the seed! So
#we don't do lottery with pseudo random number generators


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535806 , -0.5716629 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [17]:
#shuffle the order of elements in a tensor
#e.g. we don't want the first 500 images of cats then the last 500 of dogs
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled




<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [18]:
#shuffle it now
tf.random.shuffle(not_shuffled, seed=42)
#or rather to avoid a mix up
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Note now docs on random seed generation!

In [19]:
#if want shuffled tensors to be in the same order, use global level random seed
#in addition to operation level random seed

#tf.ones a tensor of all ones!
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros(shape=(3,4)) #tensor is all zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [21]:
#Turn teh NumPy arrays into tensors! Tensors we can run much faster
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #numpy array range 1-25, int32
print(numpy_A)
# note X = tf.constant(some_matrix)
# and lower case for vectors y = tf.constant(some_vector)

A = tf.constant(numpy_A)
A

# change dimensions for the tensor that we converted the numpy array into

B = tf.constant(numpy_A, shape=(2,3,4)) # so 3 dimensions now
B

# 2,3,4 shape is fine since we had 24 elements in our array i.e. 2*3*4=24
# but we can't have dimensions which don't match the number of elements so e.g. 
# 3,8 shape is fine too etc.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Getting information from Tensors


In [22]:
# Shape = length (number elements) of each of dimensions of a tensor
# Rank = scalar rank=0, vector rank=1, matrix rank=2, tensor rank=n  
# Dimension or axis = a particular dimension
# size = total number items in the tensor

#create 4 dimensional tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
#get various attributes of tensor
print('Datatype of every element: ', rank_4_tensor.dtype)
print('Number of dimensions: ', rank_4_tensor.ndim)
print('Shape of tensor: ', rank_4_tensor.shape)
print('Elements along the 0 axis: ', rank_4_tensor.shape[0])
print('Elements along the last axis: ', rank_4_tensor.shape[-1])
print('Total number of elements: ', tf.size(rank_4_tensor))
print('Total number of elements: ', tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements:  120


Indexing tensors just like lists


In [26]:
# get first 2 elements from each dimension 
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
#get first element from each dimension except 4th dimension
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
#first elements from each dimension except 3rd dimension
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [29]:
#add an extra dimension to the end of a tensor
#create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

#get last elements
rank_2_tensor[:, -1]

#now add extra dimension with tf.new axis method
rank_3_tensor = rank_2_tensor[..., tf.newaxis] #... is every axis before the new one
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [30]:
# or alternative is expand_dims
tf.expand_dims(rank_2_tensor, axis=-1) #-1 being expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
# expand the zero axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

Manipulating tensors (tensor operations)


In [32]:
#basic operations + - * / elementwise operations

# add values to a tensor using addition operator

tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10 # remember original tensor is not changed tho

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [33]:
#Multiply
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [34]:
#Subract
tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [35]:
# use the tensorflow built-in function too tf.math.x stick we these instead of python ones FASTER
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [37]:
tf.subtract(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

MATRIX MULTIPLICATION - one of most common tensor operations! 

In [38]:
#to multiply a matrix by another matrix we need to the do DOT PRODUCT of
#rows and columns
#DOT PRODUCT is where we multiply matching numbers, then sum up see matrixmultiplication.xyz
#for some demos

tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
#matrix multiplication with python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
tensor_1 = tf.constant([[10,7],
                        [3,4],
                        [6,3]])
tensor_2 = tf.constant([[10,7],
                        [3,4]])
tf.matmul(tensor_1, tensor_2) #multiply some different shaped tensors

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37],
       [ 69,  54]], dtype=int32)>

In [41]:
tensor_1.shape, tensor_2.shape #see these are different shapes

(TensorShape([3, 2]), TensorShape([2, 2]))

In [42]:
#what about these? These are the SAME shape
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [43]:
#tf.matmul(X,Y) #can they be multiplied?


In [44]:
#Rules
#1. Inner dimensions must match
#2. Resulting matrix has the shape of the outer dimensions



In [45]:
#what about these? Inner dimensions are match right
X1 = tf.constant([[1,2,3],
                 [3,4,5],
                 [5,6,7]])
Y1 = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X1,Y1

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [46]:
tf.matmul(X1,Y1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 58,  64],
       [112, 124],
       [166, 184]], dtype=int32)>

In [47]:
#Lets do a reshape of the other ones Y and X here's there shape now
#So here they are right now 3,2 and 3,2
X,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [48]:
#Lets reshape Y to 2,3
Y = tf.reshape(Y, shape=(2,3))
print(Y)

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [49]:
#So do the inner dimensions match now?
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [50]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
# Can do the same with transpose see what is the difference!
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

You can perform matrix multiplication with 
1. tf.matmul()
2. tf.tensordot()

In [52]:
# Perform dot product on X and Y (requires X and Y to be transposed)
# Here are the tensors again
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [53]:
#so multiply these 
tf.tensordot(tf.transpose(X),Y, axes=1)


## [1 3 5] * [7 8]    = [89 98]
## [2 4 6]   [9 10]     [116 128]
##    X      [11 12]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [54]:
# Matrix multplication between X and Y with Y transposed this time
tf.matmul(X, tf.transpose(Y))
 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [55]:
# So above we are going to do X*Y with
X,tf.transpose(Y)

# So like this
#
# [1 2] * [7 9 11]  = [ 23 29 35]
# [3 4]   [8,10,12]   [ 53 67 81]
# [5 6]               [ 83 105 127]

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [56]:
# Now again, but Y is reshaped instead of transposed
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [57]:
#So above we are doing X*Y with
X, tf.reshape(Y, shape=(2,3))

## So like this
#
# [1 2] * [7 8 9]      = [27 30 33]
# [3 4]   [10, 11, 12]   [61 68 75]
# [5 6]                  [95 106 117]

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [58]:
#Check values of Y reshape Y and transposed Y altogether

print('Normal Y: ')
print(Y, "\n")

print('Y reshaped to 2,3): ')
print(tf.reshape(Y, (2,3)), "\n")

print('Y transposed: ')
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to 2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Changing the datatype of a tensor


In [59]:
#create a new tensor

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [60]:
C = tf.constant([10, 11])
C.dtype

tf.int32

In [61]:
#Changing from float32 to float16 # 16 bit dtype run faster 
D = tf.cast(B, dtype=tf.float16)
D, B

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [62]:
#Chang int32 to float32
E = tf.cast(C,dtype=tf.float32)
E, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>)

Aggregating Tensors


In [63]:
#multiple values down to a smaller number of values

# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [64]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [65]:
# Here are some more:
# 1. Min
# 2. Max
# 3. Mean
# 4. Sum


In [66]:
E = tf.constant(np.random.randint(0, 100, 50)) #0-100 size=50
E
E.shape, E.ndim

# FIND THE MIN
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [67]:
tf.reduce_max(E) #MAX

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [68]:
#MEAN
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [69]:
#SUM
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2741>

In [70]:
import tensorflow_probability as tfp

Using https://www.tensorflow.org/probability/api_docs/python/tfp

In [71]:
#variability
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=805>

In [72]:
#SD well not for ints, so change to float
F = tf.cast(E, dtype=tf.float32)
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float32, numpy=28.367369>

In [73]:
#Find variance of E tensor
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))
#very similar to using stats.variance

<tf.Tensor: shape=(), dtype=float32, numpy=804.7076>

Find positional max and min


In [74]:
# create tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [75]:
#at which index does the max value occur? find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [76]:
#index on largest value position so we can see what the value is
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
#find max value for F tensor. So yes this is the same
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [78]:
assert F[tf.argmax(F)] == tf.reduce_max(F) #checking for equality

In [79]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [80]:
#now for positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [81]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [82]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [83]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

Squeezing a tensor (removing all single dimensions)


In [84]:
#create tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape =(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [85]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [86]:
G_squeezed = tf.squeeze(G) #removes dimensions of size 1 from the shape of a tensor
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [87]:
G_squeezed.shape

TensorShape([50])

One-hot encoding

In [88]:
#list of values
some_list = [0,1,2,3] # e.g. red green blue purple

In [89]:
#one-hot encode
tf.one_hot(some_list, depth=4) #depth =4

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
#specify custom values for on-hot encoding
tf.one_hot(some_list, depth=4, on_value="On", off_value="Off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>

In [91]:
#one-hot encode
tf.one_hot(some_list, depth=3) #depth =3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [92]:
### Squaring, log, sqrt

In [93]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [94]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [95]:
tf.sqrt(tf.cast(H, dtype=tf.float32)) #cast to a float since sqrt would not take integer

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [96]:
tf.math.log(tf.cast(H, dtype=tf.float32)) #again cast to a float since log would not take integer

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors and Numpy

In [97]:
#create a tensor from a numpy array

J = tf.constant(np.array([3.,7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [98]:
#convert tensor back to numpy array
H = np.array(J)
H

array([ 3.,  7., 10.])

In [99]:
#convert J to numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [100]:
#Default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.])) #float 64
tensor_J = tf.constant([3.,7,10.]) # float 32
numpy_J.dtype, tensor_J.dtype


(tf.float64, tf.float32)

In [101]:
tf.config.list_physical_devices() #what units are available

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [102]:
!nvidia-smi #whats the GPU?

Mon Aug 16 18:49:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    28W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------